// Minimal ABI subset for End User flow calldata encoding.
// Source of truth: contracts/out/Marketplace.sol/Marketplace.json (generated by
// `forge build`). We hand-mirror only the functions the End User flow needs
// (createAndFundAgent, fundAgent, withdrawAgentBalance, rateTask) so this
// module has no runtime filesystem dependency and tests can import it cleanly.
//
// TODO(track-d): when `lib/abi/Marketplace.ts` (frontend-side type-safe ABI)
// lands, consolidate both consumers on the same export.

export const MARKETPLACE_ABI = [
  {
    type: "function",
    name: "createAndFundAgent",
    stateMutability: "payable",
    inputs: [
      { name: "maxPerCall", type: "uint128" },
      { name: "dailySpendCap", type: "uint128" },
      { name: "operator", type: "address" },
      { name: "name", type: "string" },
      { name: "goal", type: "string" },
    ],
    outputs: [{ name: "agentId", type: "uint256" }],
  },
  {
    type: "function",
    name: "fundAgent",
    stateMutability: "payable",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawAgentBalance",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "amount", type: "uint128" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "rateTask",
    stateMutability: "nonpayable",
    inputs: [
      { name: "taskId", type: "bytes32" },
      { name: "stars", type: "uint8" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "registerTool",
    stateMutability: "nonpayable",
    inputs: [
      { name: "endpoint", type: "string" },
      { name: "schemaHash", type: "bytes32" },
      { name: "price", type: "uint128" },
      { name: "name", type: "string" },
      { name: "description", type: "string" },
      { name: "payout", type: "address" },
    ],
    outputs: [{ name: "toolId", type: "uint256" }],
  },
] as const;

// Address of the deployed Marketplace contract. Until Track D ships the real
// deploy, we return a deterministic placeholder so the calldata roundtrip is
// testable. The frontend reads this from env; we mirror that fallback here.
export const MARKETPLACE_ADDRESS =
  (process.env.MARKETPLACE_ADDRESS as `0x${string}` | undefined) ??
  ("0x000000000000000000000000000000000000dEaD" as const);
