/**
 * scripts/sync-abi.ts
 *
 * Reads compiled Foundry artifacts from contracts/out/<Name>.sol/<Name>.json
 * and writes typed TS exports at lib/abi/<Name>.ts. The generated files use
 * `as const` so viem's type inference works end-to-end (event arg names,
 * function param types, return types).
 *
 * Run via:  npm run sync:abi
 *
 * If contracts/out/ is missing, the script prints a clear error pointing
 * to `cd contracts && forge build`.
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const REPO_ROOT = resolve(__dirname, "..");
const OUT_DIR = join(REPO_ROOT, "contracts", "out");
const ABI_DIR = join(REPO_ROOT, "lib", "abi");

// Contracts we want typed bindings for. Names must match the Solidity file +
// contract names (Foundry writes artifacts as out/<File>.sol/<Contract>.json).
const TARGETS: ReadonlyArray<{ file: string; contract: string }> = [
  { file: "Marketplace.sol", contract: "Marketplace" },
  { file: "Passport.sol", contract: "Passport" },
];

function readArtifact(file: string, contract: string): unknown {
  const path = join(OUT_DIR, file, `${contract}.json`);
  if (!existsSync(path)) {
    throw new Error(
      `Missing Foundry artifact at ${path}. Run \`cd contracts && PATH="$HOME/.foundry/bin:$PATH" forge build\` first.`,
    );
  }
  const raw = readFileSync(path, "utf8");
  return JSON.parse(raw);
}

function emitAbi(contract: string, abi: unknown): string {
  const json = JSON.stringify(abi, null, 2);
  const header = `// AUTO-GENERATED by scripts/sync-abi.ts. DO NOT EDIT.\n// Source: contracts/out/${contract}.sol/${contract}.json\n// Regenerate with: npm run sync:abi\n`;
  return `${header}\nexport const ${contract}Abi = ${json} as const;\n\nexport type ${contract}Abi = typeof ${contract}Abi;\n`;
}

function main(): void {
  mkdirSync(ABI_DIR, { recursive: true });
  for (const { file, contract } of TARGETS) {
    const artifact = readArtifact(file, contract) as { abi?: unknown };
    if (!Array.isArray(artifact.abi)) {
      throw new Error(`Artifact ${file}/${contract}.json is missing an "abi" array`);
    }
    const outPath = join(ABI_DIR, `${contract}.ts`);
    writeFileSync(outPath, emitAbi(contract, artifact.abi));
    console.log(`[sync-abi] wrote ${outPath} (${artifact.abi.length} entries)`);
  }

  // Refresh the placeholder addresses.example.json so it always documents the
  // expected shape — even before a local deploy runs.
  const examplePath = join(ABI_DIR, "addresses.example.json");
  if (!existsSync(examplePath)) {
    writeFileSync(
      examplePath,
      `${JSON.stringify(
        {
          chainId: 10143,
          network: "monad-testnet",
          passport: "0x0000000000000000000000000000000000000000",
          marketplace: "0x0000000000000000000000000000000000000000",
        },
        null,
        2,
      )}\n`,
    );
    console.log(`[sync-abi] wrote ${examplePath}`);
  }
}

main();
